dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3
  google_fonts: ^6.1.0
  animate_do: ^3.3.2 # For those smooth, professional animations
